version = "1.0"

[main]
name.en = "Information about your app's code"
name.fr = "Information à propos de votre propre code"

    [main.custom_code]
        [main.custom_code.requirements_path]
        ask = "path to your requirements.txt file"
        type = "path"
        optional = true
        help = "Relative path to your requirement file, including it's name"
