#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)
data_dir=$(ynh_app_setting_get --key=data_dir)

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply

    #TODO : add password question to configuration panel
    password=""
    # Set new password
    if [[ -n "$password" ]]; then
        ynh_print_info "Changing password for user $app"
        chpasswd <<< "${app}:${password}"
    fi

    if [[ -n "$requirements_path" ]]; then
        ynh_print_info "Installing python custom requirements"
        # Install user's custom requirements
        "$install_dir/venv/bin/pip" install -r "$data_dir/$requirements_path"
    fi

    ynh_script_progression "Starting $app's systemd service..."
    ynh_systemctl --service="$app" --action="restart"
}

ynh_app_config_run "$1"
