#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

# Keys of the config panel
requirements_path="requirements.txt"
ynh_app_setting_set --key="requirements_path" --value="$requirements_path"

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression "Installing FastAPI via Python virtualenv..."

ynh_config_add --template="requirements.txt" --destination="$install_dir/requirements.txt"

myynh_setup_python_venv

#=================================================
# APP INITIAL CONFIGURATION
# ================================================
ynh_script_progression "Adding $app configuration files..."

ynh_config_add --template="gunicorn.conf.py" --destination="$install_dir/gunicorn.conf.py"
ynh_config_add --template="__init__.py" --destination="$data_dir/FastAPIAppFolder/__init__.py"

chown -R "$app:" "$data_dir"

# Add the password to this user
chpasswd <<< "${app}:${password}"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Gunicorn running a FastAPI app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
chown -R "$app:$app" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
