#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Legacy settings
ynh_app_setting_delete --key="log_file"

#=================================================
# PYTHON VIRTUALENV
#=================================================
ynh_script_progression "Upgrading FastAPI via Python virtualenv..."

ynh_config_add --template="requirements.txt" --destination="$install_dir/requirements.txt"

myynh_setup_python_venv

#=================================================
# UPDATE A CONFIG FILE
# ================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="gunicorn.conf.py" --destination="$install_dir/gunicorn.conf.py"
ynh_config_add --template="__init__.py" --destination="$data_dir/FastAPIAppFolder/__init__.py"

chown -R "$app:" "$data_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Gunicorn running a FastAPI app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
chown -R "$app:$app" "/var/log/$app"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
